REPORT_PEC = "PEC Verification Report"

TITLE = "FIT"
REPORT = "Freezing Internet Tool Report"
INDEX = "Index"

DESCRIPTION = "FIT - Freezing Internet Tool is an application for forensic acquisition of content such as web pages, " \
              "emails, and social media directly from the internet. FIT is a FLOSS tool: an acronym for 'Free/Libre and " \
              "Open Source Software.' It is a type of software whose source code is made available to the public and can" \
              " be used, modified, and distributed by anyone, according to the terms of a specific free and open" \
              " source software license. This means that, compared to proprietary software, FLOSS software offers " \
              "greater freedom and flexibility to users, who can customize it to meet their needs, improve it, and " \
              "distribute it without restrictions. Additionally, being open to review by other developers, FLOSS " \
              "software often benefits from a more transparent and inclusive collaborative development process. " \
              "FIT has been developed using the Python programming language, implementing a modular architecture. " \
              "FIT can be downloaded from the following link: {}.<br><br>" \
              "A forensic browser is software used to analyze and retrieve data from electronic devices such as computers, " \
              "smartphones, or tablets during forensic investigations. This software allows access to device usage information " \
              "such as activity history, files and documents, text messages, images, and much more, providing evidence that " \
              "can be used in a legal case."

T1 = "Freezing Internet Tool"
T2 = "General Information"
CASEINFO = "Case Information"
CASEDATA = "Case Data"
TYPED = "Acquisition Type"
DATE = "Acquisition Date"

T3 = "Data Ownership Verification"
T3DESCR = "During the acquisition, the user browsed various websites. FIT performed verification for each connection using " \
          "specially implemented routines. In particular, the following information was provided to determine the ownership " \
          "of the involved domains:"

T4 = "Digital Forensics"
T4DESCR = "Digital forensics is the scientific and technological application of forensic principles to the collection, " \
          "preservation, analysis, and presentation of digital data in a legal context. This discipline is used to investigate " \
          "cybercrimes such as fraud, data theft, or malware dissemination, and to recover and analyze information from " \
          "electronic devices such as computers, smartphones, and tablets. Digital forensics involves the use of specialized " \
          "tools to analyze digital data and ensure the validity of evidence in a legal context. The work of digital forensics " \
          "professionals is crucial in assisting investigative agencies and courts in identifying and punishing cybercriminals " \
          "and ensuring justice."

TITLECC = "Chain of Custody"

CCDESCR = "The chain of custody is an important concept in forensic science that describes the control and documentation of " \
          "the movement and handling of evidence during an investigation or legal process. The chain of custody ensures that " \
          "the evidence is authentic, unaltered, and uncontaminated, and that its integrity is maintained from the moment of " \
          "collection until its use in court. Maintaining a reliable chain of custody is essential to ensure that the evidence " \
          "is valid and suitable to support conclusions in a legal context."

TITLEH = "Hash"
HDESCR = "The hash of digital evidence is a unique value that represents digital data and is used to verify the integrity " \
         "and authenticity of the evidence. A hash is calculated using a one-way cryptographic algorithm that transforms " \
         "data into a fixed-length character string. If the original data is modified, the hash also changes, making it " \
         "easy to detect any alterations. In a legal context, the hash of digital evidence is often used to verify that " \
         "the original data has not been altered during the process of collecting, preserving, and presenting the evidence. " \
         "Maintaining a record of the hash of digital evidence helps ensure its integrity and ensures that it is suitable " \
         "to support conclusions in a legal case."

T5 = "Files Produced by the System"
T5DESCR = "During the acquisition, the system produced a series of files (such as screenshots, videos of the entire browsing session, " \
          "network traffic logs, etc.), identified in the following table."

NAME = "File Name"
DESCR = "Description"
AVID = "Video Acquisition"
HASHD = "File Containing Hashes of Files"
LOGD = "Information Generated by System Components"
PCAPD = "Network Traffic Recording"
ZIPD = "Archive Containing the Acquisition"
WHOISD = "Whois File"
PNGD = "Page Screenshot"
DUMPD = "Traffic Analysis File"
HEADERSD = "Request Headers"
NSLOOKUPD = "DNS Records"
CERD = "Server Certificate"
SSLKEYD = "SSL Keys"
TRACEROUTED = "Packet Traceroute"

T6 = "Hash of Files Produced by the System"
T6DESCR = "Each file produced by the infrastructure is validated by calculating its hash. "
"With this procedure, each individual file produced is unchangeable and can also be provided individually " \
"while maintaining the validity of the Chain of Custody."

T7 = "Files Produced by the User"
T7DESCR = "All files produced by the user during the acquisition are collected within a compressed folder with the .zip extension. " \
          "For each of these files, the size is reported in bytes."
T8 = "Page Screenshot"
T8DESCR = "The screenshots of the page visited during the acquisition are displayed below."
T9 = "Video acquisition"
T9DESCR = "Below is the hyperlink to the video recording."
VERIFI_OK = "The verification of the PDF report timestamp has provided a positive result. " \
            "Below are the details regarding the verification outcome, the file, the hashing algorithm, " \
            "and the Time Stamp Authority service used for the check."
VERIFI_KO = "The verification of the PDF report timestamp has provided a negative result. " \
            "Below are the details regarding the verification outcome, the file, the hashing algorithm, " \
            "and the Time Stamp Authority service used for the check."
VERIFICATION = "Report Timestamp Verification"

CASE = "Client / Case"
LAWYER = "Lawyer"
PROCEEDING = "Proceeding Type"
COURT = "Court"
NUMBER = "Proceeding Number"
ACQUISITION_TYPE = "Acquisition Type"
ACQUISITION_DATE = "Acquisition Date"
NOT_PRODUCED = "File not produced."
SIZE = "Size: "
VIDEO_LINK = "Link to the video"
COMPLETE_SCREENSHOT = "Full screenshot"
RELEASES_LINK = "<a href='https://github.com/fit-project/fit/releases'>Freezing Internet Tool - Releases</a>"